"""Shared helpers for the report scripts: paths, plotting style, LaTeX number macros and tables."""
import os
import glob
import pickle

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")
LATEX = os.path.join(HERE, "..", "latex")
FIGS = os.path.join(LATEX, "figs")
GEN = os.path.join(LATEX, "generated")
os.makedirs(FIGS, exist_ok=True)
os.makedirs(GEN, exist_ok=True)

# colour roles (validated categorical palette: blue, orange, aqua, yellow) and neutral greys
BLUE, ORANGE, AQUA, YELLOW = "#2a78d6", "#eb6834", "#1baf7a", "#eda100"
INK, GREY, LIGHT = "#0b0b0b", "#6b6a66", "#b9b8b0"
RUNC = {"a": BLUE, "b": ORANGE, "c": AQUA, "d": YELLOW}

plt.rcParams.update({
    "font.family": "serif", "font.serif": ["STIXGeneral", "DejaVu Serif"], "mathtext.fontset": "stix",
    "font.size": 8, "axes.titlesize": 8, "axes.labelsize": 8, "legend.fontsize": 7,
    "xtick.labelsize": 7, "ytick.labelsize": 7, "axes.spines.top": False, "axes.spines.right": False,
    "axes.linewidth": 0.6, "xtick.major.width": 0.6, "ytick.major.width": 0.6, "lines.linewidth": 1.2,
    "legend.frameon": False, "savefig.bbox": "tight", "savefig.pad_inches": 0.02, "pdf.fonttype": 42,
    "axes.titlepad": 3,
})
W1, W2 = 3.4, 7.0          # single- and double-column widths [in]


def load_all(pattern):
    out = {}
    for p in sorted(glob.glob(os.path.join(RES, pattern))):
        out[os.path.basename(p)[:-4]] = pickle.load(open(p, "rb"))
    return out


def savefig(fig, name):
    fig.savefig(os.path.join(FIGS, name + ".pdf"))
    plt.close(fig)


class Macros:
    """Collect \\newcommand macros for numbers quoted in the text."""

    def __init__(self, fname):
        self.fname, self.items = fname, {}

    def __setitem__(self, key, value):
        assert key.isalpha(), key
        self.items[key] = value

    def write(self):
        with open(os.path.join(GEN, self.fname), "w") as f:
            f.write("% generated by the report scripts -- do not edit\n")
            for k, v in sorted(self.items.items()):
                f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")


def write_tex(name, text):
    with open(os.path.join(GEN, name), "w") as f:
        f.write("% generated by the report scripts -- do not edit\n" + text)


def fmt(x, nd=2):
    return f"{x:.{nd}f}"


def sci(x):
    """x in LaTeX scientific notation, e.g. $8.8\\times10^{-4}$."""
    m, e = f"{x:.1e}".split("e")
    return f"${m}\\times10^{{{int(e)}}}$"


def pct(x):
    return f"{100 * x:.0f}"


def bic_weights(recs, names, n):
    """BIC weights over a subset of candidates, from stored k and chi2 (known noise)."""
    bic = np.array([recs[m]["chi2"] + recs[m]["k"] * np.log(n) for m in names])
    w = np.exp(-(bic - bic.min()) / 2)
    return dict(zip(names, w / w.sum()))
