"""
Data loader for v2 in silico datasets (generated by datagen/generate_v2.py).

Key differences from in_silico_loader.py (v1):
  - No experimental_df dependency — data is already at 100 uniform timepoints
  - Supports dataset_type: "concentrations", "rates", or "hybrid"
  - StandardScaler fitted on training split only (no leakage into val/test)
  - Stratified train/val/test split (equal class balance in each split)
  - Explicit model_id → integer label mapping stored in label_map
"""

import os
import glob
import re
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Default model IDs for the 15-model selection
DEFAULT_MODEL_IDS = list(range(21, 32))   # models 21–31

# Feature names for each dataset type
FEATURE_NAMES = {
    "concentrations": ["X", "S1", "S2", "P", "V", "F/V"],
    "rates":          ["mu_obs", "q_S1", "q_S2", "q_P", "F/V"],
    "hybrid":         ["X", "S1", "S2", "P", "V", "F/V", "mu_obs", "q_S1", "q_S2", "q_P", "F/V"],
}


class KineticsDataset(Dataset):
    """Simple wrapper around pre-processed numpy arrays."""

    def __init__(self, X: np.ndarray, y: np.ndarray):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


def load_v2_dataloaders(
    data_dir: str,
    dataset_type: str = "concentrations",
    model_ids: list = None,
    train_frac: float = 0.70,
    val_frac:   float = 0.15,
    batch_size: int   = 128,
    normalize:  bool  = True,
    seq_len:    int   = 100,
    seed:       int   = 42,
):
    """
    Load v2 in silico data and return train/val/test DataLoaders.

    Parameters
    ----------
    data_dir     : path to generated_v2/ directory
    dataset_type : "concentrations", "rates", or "hybrid"
    model_ids    : list of model IDs to include (default: all 15)
    train_frac   : fraction of data for training
    val_frac     : fraction of data for validation (test = remainder)
    batch_size   : DataLoader batch size
    normalize    : if True, apply per-feature StandardScaler (fit on train only)
    seq_len      : number of timepoints to use per sequence (≤ 100).
                   Uniformly subsamples the 100-point sequences.
                   Use this to simulate different offline sampling frequencies
                   or to match the resolution of experimental data.
    seed         : random seed for reproducibility

    Returns
    -------
    train_loader : DataLoader
    val_loader   : DataLoader
    test_loader  : DataLoader
    scaler       : fitted StandardScaler (or None if normalize=False)
    meta         : dict with label_map, feature_names, input_dim, n_classes
    """
    if model_ids is None:
        model_ids = DEFAULT_MODEL_IDS

    type_dir = os.path.join(data_dir, dataset_type)
    if not os.path.isdir(type_dir):
        raise FileNotFoundError(f"Dataset directory not found: {type_dir}")

    # Build label map: model_id → integer class label (sorted order)
    label_map = {mid: idx for idx, mid in enumerate(sorted(model_ids))}

    X_list, y_list = [], []

    for mid in sorted(model_ids):
        fpath = os.path.join(type_dir, f"model{mid}.npy")
        if not os.path.exists(fpath):
            raise FileNotFoundError(f"Missing file: {fpath}")

        data = np.load(fpath)          # (N, T, F)
        n_stored = data.shape[1]

        # ── Backward compat: if rates has 4 features, append F/V from conc ──
        if dataset_type == "rates" and data.shape[2] == 4:
            conc_path = os.path.join(data_dir, "concentrations", f"model{mid}.npy")
            if os.path.exists(conc_path):
                conc_data = np.load(conc_path)       # (N, T, 6)
                FV_col    = conc_data[:, :, 5:6]     # (N, T, 1) — F/V is feature index 5
                data      = np.concatenate([data, FV_col], axis=2)   # (N, T, 5)

        label = label_map[mid]
        X_list.append(data)
        y_list.append(np.full(data.shape[0], label, dtype=np.int64))

    X = np.concatenate(X_list, axis=0)   # (N_total, T, F)
    y = np.concatenate(y_list, axis=0)   # (N_total,)

    # ── Subsample timepoints ──────────────────────────────────────────
    T_full = X.shape[1]
    if seq_len < T_full:
        idx = np.round(np.linspace(0, T_full - 1, seq_len)).astype(int)
        X   = X[:, idx, :]
    elif seq_len > T_full:
        raise ValueError(
            f"seq_len={seq_len} > stored timepoints ({T_full}). "
            "Cannot upsample — regenerate data or reduce seq_len."
        )

    N, T, F = X.shape

    # ── Stratified split ─────────────────────────────────────────────
    test_frac = 1.0 - train_frac - val_frac
    assert test_frac > 0, "train_frac + val_frac must be < 1.0"

    # First split: train vs (val + test)
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=(val_frac + test_frac),
        stratify=y, random_state=seed,
    )
    # Second split: val vs test
    val_ratio_of_temp = val_frac / (val_frac + test_frac)
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=(1.0 - val_ratio_of_temp),
        stratify=y_temp, random_state=seed,
    )

    # ── Normalisation (fit on train, apply to all) ────────────────────
    scaler = None
    if normalize:
        scaler = StandardScaler()
        # Reshape to (N*T, F) → fit → reshape back
        X_train = scaler.fit_transform(
            X_train.reshape(-1, F)
        ).reshape(X_train.shape)

        X_val  = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
        X_test = scaler.transform(X_test.reshape(-1, F)).reshape(X_test.shape)

    # ── DataLoaders ───────────────────────────────────────────────────
    train_loader = DataLoader(
        KineticsDataset(X_train, y_train),
        batch_size=batch_size, shuffle=True, drop_last=True,
    )
    val_loader = DataLoader(
        KineticsDataset(X_val, y_val),
        batch_size=batch_size, shuffle=False,
    )
    test_loader = DataLoader(
        KineticsDataset(X_test, y_test),
        batch_size=batch_size, shuffle=False,
    )

    feature_names = FEATURE_NAMES.get(dataset_type, [f"feat_{i}" for i in range(F)])

    meta = {
        "label_map":     label_map,
        "label_names":   [f"model{mid}" for mid in sorted(model_ids)],
        "feature_names": feature_names,
        "input_dim":     F,
        "n_classes":     len(model_ids),
        "n_train":       len(X_train),
        "n_val":         len(X_val),
        "n_test":        len(X_test),
        "dataset_type":  dataset_type,
        "seq_len":       X.shape[1],
    }

    print(f"Dataset: {dataset_type}  |  {N} total samples  |  {len(model_ids)} classes")
    print(f"  Train: {len(X_train)}  Val: {len(X_val)}  Test: {len(X_test)}")
    print(f"  Input dim: {F}  |  Sequence length: {X.shape[1]}")

    return train_loader, val_loader, test_loader, scaler, meta


# ── Regressor dataloader ──────────────────────────────────────────────────────

def load_regressor_dataloaders(
    data_dir: str,
    dataset_type: str = "concentrations",
    model_ids: list = None,
    train_frac: float = 0.70,
    val_frac:   float = 0.15,
    batch_size: int   = 256,
    seq_len:    int   = 100,
    seed:       int   = 42,
):
    """
    Load v2 in silico data for the SharedEncoderRegressor.

    For each model, returns (X, y_norm) where:
      - X is StandardScaler-normalised input (scaler fitted across ALL models)
      - y_norm is the kinetic parameter vector normalised to [0,1] using
        the LHS sampling bounds from param_ranges_v2.py

    Training in [0,1] parameter space makes the MSE loss fair across all
    parameters regardless of their physical scale.

    Parameters
    ----------
    data_dir, dataset_type, model_ids, train_frac, val_frac, batch_size,
    seq_len, seed : same semantics as load_v2_dataloaders

    Returns
    -------
    train_loaders : {model_id: DataLoader}   (X_norm, y_norm)
    val_loaders   : {model_id: DataLoader}
    test_loaders  : {model_id: DataLoader}
    x_scaler      : fitted StandardScaler for X
    meta          : dict with param_names, bounds, input_dim, seq_len per model
    """
    from datagen.param_ranges_v2 import PARAM_RANGES, get_param_bounds

    if model_ids is None:
        model_ids = DEFAULT_MODEL_IDS

    type_dir = os.path.join(data_dir, dataset_type)

    # ── Load all X and y data ─────────────────────────────────────────
    X_all_list = []   # for fitting the shared X scaler
    data_per_model = {}

    for mid in sorted(model_ids):
        x_path = os.path.join(type_dir, f"model{mid}.npy")
        y_path = os.path.join(type_dir, f"params_model{mid}.csv")

        if not os.path.exists(x_path):
            raise FileNotFoundError(f"Missing: {x_path}")
        if not os.path.exists(y_path):
            raise FileNotFoundError(f"Missing: {y_path}")

        import pandas as pd
        X = np.load(x_path)        # (N, T, F)
        y = pd.read_csv(y_path).values.astype(np.float32)   # (N, P)

        # Backward compat: if rates has 4 features, append F/V from conc
        if dataset_type == "rates" and X.shape[2] == 4:
            conc_path = os.path.join(data_dir, "concentrations", f"model{mid}.npy")
            if os.path.exists(conc_path):
                conc_data = np.load(conc_path)
                X = np.concatenate([X, conc_data[:, :, 5:6]], axis=2)

        # Subsample timepoints
        T_full = X.shape[1]
        if seq_len < T_full:
            idx = np.round(np.linspace(0, T_full - 1, seq_len)).astype(int)
            X   = X[:, idx, :]

        # Normalise y to [0,1] using LHS bounds
        lbs, ubs = get_param_bounds(mid)
        lbs = np.array(lbs, dtype=np.float32)
        ubs = np.array(ubs, dtype=np.float32)
        ranges = ubs - lbs
        if np.any(ranges == 0):
            zero_params = [list(PARAM_RANGES[mid].keys())[i]
                           for i in np.where(ranges == 0)[0]]
            raise ValueError(
                f"model{mid} has zero-width parameter range(s): {zero_params}. "
                "Fix bounds in param_ranges_v2.py — division by zero produces NaN targets."
            )
        y_norm = (y - lbs) / ranges
        y_norm = np.clip(y_norm, 0.0, 1.0)   # safety clip for edge cases

        data_per_model[mid] = {"X": X, "y_norm": y_norm, "lbs": lbs, "ubs": ubs}
        X_all_list.append(X)

    F = data_per_model[sorted(model_ids)[0]]["X"].shape[2]
    T = data_per_model[sorted(model_ids)[0]]["X"].shape[1]

    # ── Fit a single X scaler on ALL training data ────────────────────
    # First pass: collect train splits and fit scaler
    splits = {}
    for mid in sorted(model_ids):
        X = data_per_model[mid]["X"]
        y = data_per_model[mid]["y_norm"]
        N = len(X)
        test_frac = 1.0 - train_frac - val_frac
        X_tr, X_tmp, y_tr, y_tmp = train_test_split(
            X, y, test_size=(val_frac + test_frac), random_state=seed
        )
        vr = val_frac / (val_frac + test_frac)
        X_v, X_te, y_v, y_te = train_test_split(
            X_tmp, y_tmp, test_size=(1.0 - vr), random_state=seed
        )
        splits[mid] = {"X_tr": X_tr, "X_v": X_v, "X_te": X_te,
                       "y_tr": y_tr, "y_v": y_v, "y_te": y_te}

    # Fit scaler on concatenated training X
    X_train_all = np.concatenate(
        [splits[mid]["X_tr"] for mid in sorted(model_ids)], axis=0
    )
    x_scaler = StandardScaler()
    x_scaler.fit(X_train_all.reshape(-1, F))

    # ── Build per-model DataLoaders ───────────────────────────────────
    def _apply_scaler(X):
        return x_scaler.transform(X.reshape(-1, F)).reshape(X.shape)

    train_loaders, val_loaders, test_loaders = {}, {}, {}

    for mid in sorted(model_ids):
        sp = splits[mid]
        X_tr = _apply_scaler(sp["X_tr"])
        X_v  = _apply_scaler(sp["X_v"])
        X_te = _apply_scaler(sp["X_te"])

        # Use TensorDataset with explicit float32 — KineticsDataset hardcodes
        # y as torch.long (correct for classifier labels, wrong for regression)
        def _ds(X_arr, y_arr):
            return TensorDataset(
                torch.tensor(X_arr, dtype=torch.float32),
                torch.tensor(y_arr, dtype=torch.float32),
            )

        train_loaders[mid] = DataLoader(
            _ds(X_tr, sp["y_tr"]),
            batch_size=batch_size, shuffle=True, drop_last=True,
        )
        val_loaders[mid] = DataLoader(
            _ds(X_v, sp["y_v"]),
            batch_size=batch_size, shuffle=False,
        )
        test_loaders[mid] = DataLoader(
            _ds(X_te, sp["y_te"]),
            batch_size=batch_size, shuffle=False,
        )

    # ── Build meta ────────────────────────────────────────────────────
    meta = {
        "model_ids":    sorted(model_ids),
        "dataset_type": dataset_type,
        "seq_len":      T,
        "input_dim":    F,
        "param_names":  {mid: list(PARAM_RANGES[mid].keys()) for mid in model_ids},
        "model_param_counts": {mid: len(PARAM_RANGES[mid]) for mid in model_ids},
        "bounds": {
            mid: {
                "lbs": data_per_model[mid]["lbs"].tolist(),
                "ubs": data_per_model[mid]["ubs"].tolist(),
            }
            for mid in model_ids
        },
    }

    print(f"Regressor data: {dataset_type}  |  {len(model_ids)} models  |  seq_len={T}")
    for mid in sorted(model_ids):
        n_tr = len(splits[mid]["X_tr"])
        n_v  = len(splits[mid]["X_v"])
        n_te = len(splits[mid]["X_te"])
        print(f"  model{mid:<3}: train={n_tr}  val={n_v}  test={n_te}  "
              f"params={meta['model_param_counts'][mid]}")

    return train_loaders, val_loaders, test_loaders, x_scaler, meta
